# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-icon-theme.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-icon-theme.spec
    - .packit.yaml

upstream_ref: 2020.09.24
upstream_package_name: deepin-icon-theme
# downstream (Fedora) RPM package name
downstream_package_name: deepin-icon-theme

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-icon-theme.spec"
